<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;netcoreapp3.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>img\DECa.ico</ApplicationIcon>
	<LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="img\DECa.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Doc\" />
  </ItemGroup>

</Project>
